### ISSUE TITLE
Thesis Statement

### ISSUE THREAD

**Issue by pswestmore72** [ChristopheGarcia1/Crime_Analysis-#1]
Layout a concrete thesis statement using crime data as the core metric

Link/show all datasets we want to use to answer this thesis

**Comment by pswestmore72** [comment]
Food scarcity data
https://www.ers.usda.gov/data-products/food-access-research-atlas/download-the-data/

**Comment by pswestmore72** [comment]
### Proposed Thesis
Analyze Crime Data for Austin, TX (maybe Houston/all of Texas if time permits?) against other factors such as; access to food, general wealth/ home costs, school teacher: student ratio, daily weather... and offer visualizations of any trends between crime and these other factors.

**Deliverable 1 Success metrics**

- [x] Mission Statement/ Thesis
- [x] Find/Gather Datasets
- [x] Very Rough Sketch of What final dashboard/app/website will display, and how it will display it
- [x] Maybe 3-5 visualizations?
- [x] Will there be a Data Model?
- [x] Start ReadMe file to document what/how project contains

**Comment by ChristopheGarcia1** [comment]
Proposal was formed and discussed with TA's and instructor
