### ISSUE TITLE
Clean USDA data , and zip code/census tract data to merge with crime_data.csv

### ISSUE THREAD

**Issue by ChristopheGarcia1** [ChristopheGarcia1/Crime_Analysis-#10]
Most of the food insecurity data is based on census data and not zip codes. Data must be merged and together to define boundaries for  our analysis. 

- [x]  Clean and merge USDA data and zip code data

- [x]  Merge USDA data with crime data and clean.

**Comment by MoKmo176** [comment]
https://public.tableau.com/app/profile/moez.khan8652/viz/ZipCodeBubbleChart/Sheet1?publish=yes
https://public.tableau.com/app/profile/moez.khan8652/viz/PercentofTotalZipCodeBubbleChart/Sheet1?publish=yes

**Comment by ChristopheGarcia1** [comment]
We actually did this but never updated the issue. I'm going to post a new issue and post the completed crime data
