### ISSUE TITLE
Tableau Visual story board for Crime Data in Austin

### ISSUE THREAD

**Issue by pswestmore72** [ChristopheGarcia1/Crime_Analysis-#3]
Tableau Visuals for Crime Data in Austin

**Comment by pswestmore72** [comment]
taleau public link:

**Comment by MoKmo176** [comment]
https://public.tableau.com/app/profile/moez.khan8652/viz/CrimeCountsinEachAustinZip/Sheet2?publish=yes
https://public.tableau.com/app/profile/moez.khan8652/viz/TypesofCrimeinEachAustinZip/Sheet2?publish=yes
https://public.tableau.com/authoring/AvgIncomeZipCodeMostCrime/Sheet2#1
